3-е задание
htmlacademy-javascript/1347475-keksobooking-22 pull request #3
Opened 2021-02-08 19:49 UTC by ddlein

Странная ситуация...в лекции рекомендовали lodash, также в демке его использовали, но при этом ESLint ругается, хотя сами говорили что разрешено все, главное чтоб линтер не ругался

2021-02-09 10:40 UTC, PavelNyukalo requested changes

2021-02-09 10:40 UTC, PavelNyukalo commented on js/main.js
> +      guests: getRandomArbitrary(1, 4),
Вот эти цифры лучше вынести в константы, например `MIN_PRICE` и тд, так же для гостей, комнат

2021-02-09 10:40 UTC, PavelNyukalo commented on js/main.js
> +  let valueX = getRandomFixed(FROM_X, TO_X, 5);
Кол-во знаков тоже давай вынесем в константы

2021-02-09 10:40 UTC, PavelNyukalo commented on js/main.js
> +const SIMILAR_PROMO = new Array(SIMILAR_PROMO_COUNT).fill(null).map(() => createPromo())
Это у нас не неизменяемая константа, так что лучше в `camelCase` записать

2021-02-09 10:40 UTC, PavelNyukalo commented on js/main.js
> +      photos: new Array(getRandomArbitrary(1, PHOTOS.length-1)).fill(null).map(() => getRandomFeatures(PHOTOS)),
Смотри, сейчас у нас фотографии и особенности заполняются как: создаем массив случайно длины, но не больше длины исходного массива. И начинаем заполнять его результатом функции `getRandomFeatures`, которая возвращает нам рандомный элемент массива. Вроде работает, но условие задания выполняется не в полной мере - а именно: 
![image](https://user-images.githubusercontent.com/52506235/107350689-8cfa3a00-6aeb-11eb-851f-e1faf0970019.png)
![image](https://user-images.githubusercontent.com/52506235/107350861-c468e680-6aeb-11eb-9b66-09418464284b.png)
Для фото так же, просто почему-то убрали из текста задания. 
Поэтому нам надо создать функцию, которая бы генерировала и возвращала новый массив рандомной длины на основе переданного ей массива. При этом она должна еще содержать проверку, не повторяется ли особенности/фото. Если тяжко будет, то созвонимся, решим вместе

2021-02-09 18:11 UTC, ddlein commented on js/main.js
> +const TO_Y = 139.80000;
ok

2021-02-09 18:11 UTC, ddlein commented on js/main.js
> +const SIMILAR_PROMO_COUNT = 10;
ok

2021-02-09 18:11 UTC, ddlein commented on js/main.js
> +let getRandomArbitrary = (min, max) => {
ok

2021-02-09 18:11 UTC, ddlein commented on js/main.js
> +      guests: getRandomArbitrary(1, 4),
ok

2021-02-09 18:12 UTC, ddlein commented on js/main.js
> +  let valueX = getRandomFixed(FROM_X, TO_X, 5);
ok

2021-02-09 18:12 UTC, ddlein commented on js/main.js
> +const SIMILAR_PROMO = new Array(SIMILAR_PROMO_COUNT).fill(null).map(() => createPromo())
ok

2021-02-10 17:46 UTC, PavelNyukalo approved these changes

2021-02-10 17:47 UTC, merged