Задание 6.2
htmlacademy-javascript/1347475-keksobooking-22 pull request #8
Opened 2021-02-25 16:40 UTC by ddlein

2021-02-25 17:42 UTC, PavelNyukalo requested changes

2021-02-25 17:42 UTC, PavelNyukalo commented on index.html
> +          <input id="address" name="address" type="text" disabled>
Тут немного хитро с `disabled`. Поля с `disabled` не отправляются на сервер, а нам надо отправлять это поле, но чтоб оно было _только для чтения_

2021-02-25 17:42 UTC, PavelNyukalo commented on js/form.js
> +
С валидацией гостей и комнат предлагаю переписать на `setCustomValidity`, поскольку возникает вот такая ситуация.
1. Пользователь выбирает например 1 комната для 1 гостя, все норм
![image](https://user-images.githubusercontent.com/52506235/109193181-ecc63580-77b9-11eb-8ddd-0b2e68965a46.png)

![image](https://user-images.githubusercontent.com/52506235/109192362-ec796a80-77b8-11eb-8954-723da1ddf5e3.png)


2. Потом передумывает, и выбирает например 100 комнат, да, `option` получают `disabled`, но выбранное остается для 1 гостя и пользователь может это не заметить
![image](https://user-images.githubusercontent.com/52506235/109191367-eb940900-77b7-11eb-9ffa-48cf2dc13fa2.png)
И тогда у нас данные отправляются с ошибкой
![image](https://user-images.githubusercontent.com/52506235/109192960-af61a800-77b9-11eb-8bfe-5678d129fb8d.png)

![image](https://user-images.githubusercontent.com/52506235/109192021-96a4c280-77b8-11eb-8f20-0912dfad197a.png)

2021-02-25 17:42 UTC, PavelNyukalo commented on index.html
>              <div class="ad-form__photo"></div>
Напишу тут, сейчас у формы нашего объявления нет `action`, поэтому она отправляется со статусом 405 (один из статусов ошибки)

2021-02-25 17:42 UTC, PavelNyukalo commented on index.html
> +        <form action="https://22.javascript.pages.academy/keksobooking" method="post" class="map__filters" autocomplete="off">
А фильтрам `action` и `method` как раз-таки не нужен

2021-02-25 17:50 UTC, ddlein commented on index.html
> +          <input id="address" name="address" type="text" disabled>
ok

2021-02-25 18:23 UTC, ddlein commented on js/form.js
> +
ok

2021-02-26 15:41 UTC, PavelNyukalo approved these changes

2021-02-26 15:42 UTC, merged