Module7 task1
htmlacademy-javascript/1347475-keksobooking-22 pull request #9
Opened 2021-03-03 20:59 UTC by ddlein

2021-03-04 09:42 UTC, PavelNyukalo requested changes

2021-03-04 09:42 UTC, PavelNyukalo commented on js/map.js
> +}
Предлагаю функцию очистки разбить на две - первая будет отвечать за карту, вторая за очистку формы.
И тогда нам не надо будет импортировать в модуль, работающий с картой, все поля формы, которые с картой никак не связаны (кроме адреса)

2021-03-04 09:42 UTC, PavelNyukalo commented on js/map.js
> +}
`showAlert` давай в `utils.js` закинем

2021-03-04 09:42 UTC, PavelNyukalo commented on js/form.js
> +})
Насчет всплывающих окон.
1. Лучше их не скрывать, а удалять. Если мы их скрываем, при повторном нажатии и, например, снова ошибке, сообщение не показывается
2. Сейчас карта перекрывает сообщения. CSS тоже можно править
![image](https://user-images.githubusercontent.com/52506235/109943083-9f385400-7cf6-11eb-9491-ad9860a7ef2c.png)
3. Еще надо повесить обработчик на эту кнопку
![image](https://user-images.githubusercontent.com/52506235/109943184-bc6d2280-7cf6-11eb-84b7-439f8dc4c581.png)

2021-03-04 09:42 UTC, PavelNyukalo commented on js/form.js
> +const CREATE_ERROR = TEMPLATE_ERROR.cloneNode(true);
Имена им лучше без глагола, это же не функции. Можешь вообще в одну строку написать
```js
const TEMPLATE_SUCCESS = document.querySelector('#success').content.querySelector('.success').cloneNode(true);
```

2021-03-04 09:42 UTC, PavelNyukalo commented on js/map.js
> +const createMakePin = (array) => {
На консультации забыл сказать, но давай уберем Make, а то получается "создать сделать пин"

2021-03-04 17:34 UTC, ddlein commented on js/map.js
> +}
ok

2021-03-04 17:37 UTC, ddlein commented on js/map.js
> +}
ok

2021-03-04 17:38 UTC, ddlein commented on js/map.js
> +const createMakePin = (array) => {
ok

2021-03-04 19:42 UTC, ddlein commented on js/form.js
> +})
ok

2021-03-04 19:46 UTC, ddlein commented on js/form.js
> +const CREATE_ERROR = TEMPLATE_ERROR.cloneNode(true);
ok

2021-03-07 18:36 UTC, PavelNyukalo approved these changes

2021-03-07 18:36 UTC, merged